name: onyx
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.0.0+2

environment:
  sdk: any

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  video_player: any
  url_launcher: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  #  - assets/images/screen1bg.jpeg
   - assets/images/onyx.png
  #  - assets/images/screen2bg.jpeg
   - assets/images/nostalgiashop-min.jpeg
   - assets/videos/bkgvid.mp4
   - assets/images/chakra-min.jpeg
   - assets/images/mindspark-min.jpeg
   - assets/images/kavi-min.jpeg
   - assets/images/litcon-min.jpeg
   - assets/images/patron-min.jpeg
   - assets/images/prashansa-min.jpeg
   - assets/images/fetenfiesta-min.jpeg
   - assets/images/aippm-min.jpeg
   - assets/images/woi-min.jpeg
   - assets/images/ip-min.jpeg
   - assets/images/sanj-min.jpeg
   - assets/images/yat-min.jpeg
   - assets/images/vash-min.jpeg
   - assets/images/gokul-min.jpeg
   - assets/images/anshika-min.jpeg
   - assets/images/vivek-min.jpeg
   - assets/images/swati-min.jpeg
   - assets/images/rijula-min.jpeg
   - assets/images/tanushi-min.jpeg
   - assets/images/shubhi-min.jpeg
   - assets/images/aman-min.jpeg
   - assets/images/abhi-min.jpeg
   - assets/images/asthav-min.jpeg
   - assets/images/panchal-min.jpeg
   - assets/images/kar-min.jpeg
   - assets/images/andi.png
   - assets/images/team.png
   - assets/images/apt.png
   - assets/images/soc-min.jpg
   - assets/images/360a-min.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
